"""Existing-project audit for Alpha-Wiki init."""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import click

from tools.classify import classify


DOC_SUFFIXES = {".md", ".mdx", ".txt", ".json", ".yaml", ".yml", ".toml", ".graphql", ".gql", ".proto", ".sql", ".tf"}
EXCLUDED_PARTS = {
    ".git",
    ".venv",
    ".pytest_cache",
    "__pycache__",
    ".mypy_cache",
    ".ruff_cache",
    "node_modules",
    "dist",
    "build",
    "htmlcov",
    ".alpha-wiki",
    ".obsidian",
    ".wiki",
    "wiki",
    "raw",
}


@dataclass(frozen=True)
class SourceCandidate:
    path: Path
    kind: str
    raw_target: str
    wiki_slot: str
    batch: str
    reason: str


def discover_sources(root: Path) -> list[SourceCandidate]:
    root = root.resolve()
    candidates: list[SourceCandidate] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file() or _excluded(path, root):
            continue
        if path.suffix.lower() not in DOC_SUFFIXES and path.name not in {"README", "CHANGELOG"}:
            continue
        rel = path.relative_to(root)
        artifact = classify(path)
        wiki_slot, batch, reason = _route(rel, artifact.kind, artifact.suggested_slot)
        candidates.append(SourceCandidate(
            path=rel,
            kind=artifact.kind,
            raw_target=_raw_target(rel),
            wiki_slot=wiki_slot,
            batch=batch,
            reason=reason,
        ))
    return candidates


def init_audit_report(root: Path, wiki_dir: str = ".wiki") -> str:
    candidates = discover_sources(root)
    batches = _group(candidates, key=lambda item: item.batch)
    slots = _group(candidates, key=lambda item: item.wiki_slot)
    lines = [
        "# Alpha-Wiki Init Audit",
        "",
        f"- Project root: `{root.resolve()}`",
        f"- Recommended wiki dir: `{wiki_dir}`",
        f"- Candidate source files: {len(candidates)}",
        "",
        "## Project Signals",
        "",
        *[f"- {signal}" for signal in _project_signals(root)],
        "",
        "## Proposed Wiki Structure",
        "",
    ]
    for slot, items in sorted(slots.items()):
        lines.append(f"- `{wiki_dir}/{slot}/`: {len(items)} source(s)")
    lines.extend([
        "",
        "## Proposed Raw Placement",
        "",
    ])
    for item in candidates:
        lines.append(f"- `{item.path}` -> `{item.raw_target}` ({item.kind}; {item.reason})")
    lines.extend([
        "",
        "## Processing Plan",
        "",
    ])
    for batch, items in sorted(batches.items(), key=_batch_sort_key):
        lines.append(f"### {batch}")
        for item in items:
            lines.append(f"- Ingest `{item.raw_target}` -> `{wiki_dir}/{item.wiki_slot}/`")
        lines.append("")
    lines.extend([
        "## Init Decision Points",
        "",
        "- Confirm whether to copy source snapshots into `raw/` or keep a manifest that references current repo paths.",
        "- Confirm whether to process all batches now or start with Batch 1 only.",
        "- Confirm whether generated/static outputs should be excluded from future raw ingestion.",
    ])
    return "\n".join(lines).rstrip() + "\n"


def write_source_manifest(root: Path, out: Path | None = None) -> Path:
    root = root.resolve()
    target = out or root / "raw" / "docs" / "source-manifest.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    candidates = discover_sources(root)
    lines = [
        "# Source Manifest",
        "",
        "Generated by `tools/init_audit.py`. This is raw evidence for future Alpha-Wiki ingest.",
        "",
        "## Sources",
        "",
    ]
    for item in candidates:
        lines.append(f"- `{item.path}` -> `{item.raw_target}` | kind=`{item.kind}` | wiki_slot=`{item.wiki_slot}` | batch=`{item.batch}`")
    target.write_text("\n".join(lines) + "\n")
    return target


def _excluded(path: Path, root: Path) -> bool:
    rel_parts = path.relative_to(root).parts
    if any(part in EXCLUDED_PARTS for part in rel_parts):
        return True
    return "render" in rel_parts and ".wiki" in rel_parts


def _raw_target(rel: Path) -> str:
    safe_parts = [part.replace(" ", "-") for part in rel.parts]
    return str(Path("raw") / "docs" / Path(*safe_parts))


def _route(rel: Path, kind: str, suggested_slot: str | None) -> tuple[str, str, str]:
    parts = rel.parts
    name = rel.name.lower()
    if parts[0] == ".claude-plugin":
        return "contracts/rpc", "Batch 1 - contracts and decisions", "plugin metadata contract"
    if len(parts) >= 2 and parts[0] == "docs" and name.startswith("adr-"):
        return "decisions", "Batch 1 - contracts and decisions", "ADR source"
    if parts[0] == "commands":
        return "specs", "Batch 2 - command and skill manuals", "command manual"
    if parts[0] == "skills":
        return "specs", "Batch 2 - command and skill manuals", "skill manual"
    if parts[0] == "references":
        return "specs", "Batch 3 - references and examples", "reference material"
    if len(parts) >= 2 and parts[0] == "docs" and parts[1] == "superpowers":
        return "specs", "Batch 4 - archive distillation", "archive/design history"
    if parts[0] == "docs":
        return "specs", "Batch 1 - architecture and release docs", "project documentation"
    if len(parts) == 1 and rel.name in {"README.md", "CHANGELOG.md", "CLAUDE.md", "pyproject.toml"}:
        return "specs", "Batch 1 - architecture and release docs", "root project contract"
    if suggested_slot:
        return suggested_slot, "Batch 1 - contracts and decisions", "classifier suggested a concrete slot"
    return "specs", "Batch 5 - remaining documents", f"{kind} source"


def _project_signals(root: Path) -> list[str]:
    signals: list[str] = []
    for marker in ["pyproject.toml", "README.md", "CHANGELOG.md", "skills", "commands", "docs", ".claude-plugin"]:
        if (root / marker).exists():
            signals.append(f"`{marker}` present")
    return signals or ["No common project signals detected"]


def _group(items: list[SourceCandidate], key) -> dict[str, list[SourceCandidate]]:
    grouped: dict[str, list[SourceCandidate]] = {}
    for item in items:
        grouped.setdefault(key(item), []).append(item)
    return grouped


def _batch_sort_key(item: tuple[str, list[SourceCandidate]]) -> tuple[int, str]:
    label = item[0]
    for idx in range(1, 9):
        if label.startswith(f"Batch {idx}"):
            return idx, label
    return 99, label


@click.command()
@click.option("--root", type=click.Path(path_type=Path, exists=True, file_okay=False), default=Path("."), show_default=True)
@click.option("--wiki-dir", default=".wiki", show_default=True)
@click.option("--write-manifest", is_flag=True, help="Write raw/docs/source-manifest.md in addition to printing the audit.")
@click.option("--manifest-out", type=click.Path(path_type=Path), help="Override manifest output path.")
def cli(root: Path, wiki_dir: str, write_manifest: bool, manifest_out: Path | None) -> None:
    click.echo(init_audit_report(root, wiki_dir=wiki_dir))
    if write_manifest:
        target = write_source_manifest(root, out=manifest_out)
        click.echo(f"\nwrote {target}")


if __name__ == "__main__":
    cli()
